/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const SalaryRecord = IDL.Record({
  'compensation' : IDL.Nat,
  'month' : IDL.Nat,
  'salary' : IDL.Nat,
  'totalCompensation' : IDL.Nat,
  'year' : IDL.Nat,
  'paymentDate' : Time,
  'bonuses' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProduceListing = IDL.Record({
  'organic' : IDL.Bool,
  'listingId' : IDL.Nat,
  'crop' : IDL.Text,
  'listingImage' : IDL.Opt(ExternalBlob),
  'videoTour' : IDL.Opt(ExternalBlob),
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'farmer' : IDL.Principal,
});
export const InsurancePlan = IDL.Record({
  'coverageAmount' : IDL.Nat,
  'planType' : IDL.Variant({
    'premium' : IDL.Null,
    'basic' : IDL.Null,
    'comprehensive' : IDL.Null,
  }),
  'monthlyPremium' : IDL.Nat,
});
export const KnowledgeHubArticle = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'articleId' : IDL.Nat,
  'videos' : IDL.Vec(ExternalBlob),
  'images' : IDL.Vec(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'userType' : IDL.Variant({
    'other' : IDL.Null,
    'institution' : IDL.Null,
    'farmer' : IDL.Null,
  }),
  'name' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'user' : IDL.Principal,
  'messageType' : IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const FarmerCompensation = IDL.Record({
  'active' : IDL.Bool,
  'totalCompensation' : IDL.Nat,
  'pfContribution' : IDL.Nat,
  'salaryHistory' : IDL.Vec(SalaryRecord),
  'insuranceCoverage' : InsurancePlan,
  'farmer' : IDL.Principal,
  'baseSalary' : IDL.Nat,
});
export const FarmingMethods = IDL.Variant({
  'mixed' : IDL.Null,
  'organic' : IDL.Null,
  'conventional' : IDL.Null,
});
export const FarmLocation = IDL.Variant({
  'urban' : IDL.Null,
  'rural' : IDL.Null,
});
export const FarmerProfile = IDL.Record({
  'farmSize' : IDL.Nat,
  'methods' : FarmingMethods,
  'name' : IDL.Text,
  'cropTypes' : IDL.Vec(IDL.Text),
  'profilePicture' : IDL.Opt(ExternalBlob),
  'location' : FarmLocation,
});
export const AssistanceRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const AssistanceType = IDL.Variant({
  'other' : IDL.Null,
  'technicalSupport' : IDL.Null,
  'postHarvestManagement' : IDL.Null,
  'equipmentLoan' : IDL.Null,
});
export const AssistanceRequest = IDL.Record({
  'status' : AssistanceRequestStatus,
  'submittedTime' : Time,
  'requestId' : IDL.Nat,
  'videoExplanation' : IDL.Opt(ExternalBlob),
  'supportingImages' : IDL.Vec(ExternalBlob),
  'description' : IDL.Text,
  'farmer' : IDL.Principal,
  'assistanceType' : AssistanceType,
});
export const PFHistoryRecord = IDL.Record({
  'month' : IDL.Nat,
  'balance' : IDL.Nat,
  'accruedInterest' : IDL.Nat,
  'year' : IDL.Nat,
  'withdrawal' : IDL.Nat,
  'contributionAmount' : IDL.Nat,
});
export const PFAccount = IDL.Record({
  'yearlyStatements' : IDL.Vec(PFHistoryRecord),
  'totalBalance' : IDL.Nat,
  'farmer' : IDL.Principal,
});
export const InstitutionType = IDL.Variant({
  'school' : IDL.Null,
  'court' : IDL.Null,
  'university' : IDL.Null,
  'governmentOffice' : IDL.Null,
  'temple' : IDL.Null,
  'college' : IDL.Null,
});
export const InstitutionProfile = IDL.Record({
  'name' : IDL.Text,
  'instType' : InstitutionType,
  'interestedCrops' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChatMessage' : IDL.Func(
      [IDL.Text, IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null })],
      [],
      [],
    ),
  'addKnowledgeHubArticle' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Vec(ExternalBlob),
      ],
      [IDL.Nat],
      [],
    ),
  'addSalaryRecord' : IDL.Func([IDL.Principal, SalaryRecord], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'browseOrganicProduce' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ProduceListing))],
      ['query'],
    ),
  'browseProduce' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ProduceListing))],
      ['query'],
    ),
  'createOrUpdateCompensation' : IDL.Func(
      [IDL.Principal, IDL.Nat, InsurancePlan, IDL.Nat],
      [],
      [],
    ),
  'deleteFarmer' : IDL.Func([IDL.Principal], [], []),
  'deleteInstitution' : IDL.Func([IDL.Principal], [], []),
  'deleteProduceListing' : IDL.Func([IDL.Nat], [], []),
  'getAllKnowledgeHubArticles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, KnowledgeHubArticle))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getDashboardMetrics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalOrganicListings' : IDL.Nat,
          'totalListings' : IDL.Nat,
          'urbanFarmers' : IDL.Nat,
          'totalInstitutions' : IDL.Nat,
          'totalRequests' : IDL.Nat,
          'totalFarmers' : IDL.Nat,
          'ruralFarmers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getFarmerCompensation' : IDL.Func(
      [],
      [IDL.Opt(FarmerCompensation)],
      ['query'],
    ),
  'getFarmerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(FarmerProfile)],
      ['query'],
    ),
  'getMyAssistanceRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, AssistanceRequest))],
      ['query'],
    ),
  'getMyListings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ProduceListing))],
      ['query'],
    ),
  'getMyPFAccount' : IDL.Func([], [IDL.Opt(PFAccount)], ['query']),
  'getSpecificKnowledgeHubArticle' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(KnowledgeHubArticle)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listProduce' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Bool,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Nat],
      [],
    ),
  'registerFarmer' : IDL.Func([FarmerProfile], [], []),
  'registerInstitution' : IDL.Func([InstitutionProfile], [], []),
  'requestProduce' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAssistanceRequest' : IDL.Func(
      [AssistanceType, IDL.Text, IDL.Vec(ExternalBlob), IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'updateAssistanceRequestStatus' : IDL.Func(
      [IDL.Nat, AssistanceRequestStatus],
      [],
      [],
    ),
  'updatePFAccount' : IDL.Func(
      [IDL.Principal, IDL.Vec(PFHistoryRecord)],
      [],
      [],
    ),
  'updateProduceListing' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const SalaryRecord = IDL.Record({
    'compensation' : IDL.Nat,
    'month' : IDL.Nat,
    'salary' : IDL.Nat,
    'totalCompensation' : IDL.Nat,
    'year' : IDL.Nat,
    'paymentDate' : Time,
    'bonuses' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProduceListing = IDL.Record({
    'organic' : IDL.Bool,
    'listingId' : IDL.Nat,
    'crop' : IDL.Text,
    'listingImage' : IDL.Opt(ExternalBlob),
    'videoTour' : IDL.Opt(ExternalBlob),
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'farmer' : IDL.Principal,
  });
  const InsurancePlan = IDL.Record({
    'coverageAmount' : IDL.Nat,
    'planType' : IDL.Variant({
      'premium' : IDL.Null,
      'basic' : IDL.Null,
      'comprehensive' : IDL.Null,
    }),
    'monthlyPremium' : IDL.Nat,
  });
  const KnowledgeHubArticle = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'articleId' : IDL.Nat,
    'videos' : IDL.Vec(ExternalBlob),
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'userType' : IDL.Variant({
      'other' : IDL.Null,
      'institution' : IDL.Null,
      'farmer' : IDL.Null,
    }),
    'name' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'user' : IDL.Principal,
    'messageType' : IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const FarmerCompensation = IDL.Record({
    'active' : IDL.Bool,
    'totalCompensation' : IDL.Nat,
    'pfContribution' : IDL.Nat,
    'salaryHistory' : IDL.Vec(SalaryRecord),
    'insuranceCoverage' : InsurancePlan,
    'farmer' : IDL.Principal,
    'baseSalary' : IDL.Nat,
  });
  const FarmingMethods = IDL.Variant({
    'mixed' : IDL.Null,
    'organic' : IDL.Null,
    'conventional' : IDL.Null,
  });
  const FarmLocation = IDL.Variant({ 'urban' : IDL.Null, 'rural' : IDL.Null });
  const FarmerProfile = IDL.Record({
    'farmSize' : IDL.Nat,
    'methods' : FarmingMethods,
    'name' : IDL.Text,
    'cropTypes' : IDL.Vec(IDL.Text),
    'profilePicture' : IDL.Opt(ExternalBlob),
    'location' : FarmLocation,
  });
  const AssistanceRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const AssistanceType = IDL.Variant({
    'other' : IDL.Null,
    'technicalSupport' : IDL.Null,
    'postHarvestManagement' : IDL.Null,
    'equipmentLoan' : IDL.Null,
  });
  const AssistanceRequest = IDL.Record({
    'status' : AssistanceRequestStatus,
    'submittedTime' : Time,
    'requestId' : IDL.Nat,
    'videoExplanation' : IDL.Opt(ExternalBlob),
    'supportingImages' : IDL.Vec(ExternalBlob),
    'description' : IDL.Text,
    'farmer' : IDL.Principal,
    'assistanceType' : AssistanceType,
  });
  const PFHistoryRecord = IDL.Record({
    'month' : IDL.Nat,
    'balance' : IDL.Nat,
    'accruedInterest' : IDL.Nat,
    'year' : IDL.Nat,
    'withdrawal' : IDL.Nat,
    'contributionAmount' : IDL.Nat,
  });
  const PFAccount = IDL.Record({
    'yearlyStatements' : IDL.Vec(PFHistoryRecord),
    'totalBalance' : IDL.Nat,
    'farmer' : IDL.Principal,
  });
  const InstitutionType = IDL.Variant({
    'school' : IDL.Null,
    'court' : IDL.Null,
    'university' : IDL.Null,
    'governmentOffice' : IDL.Null,
    'temple' : IDL.Null,
    'college' : IDL.Null,
  });
  const InstitutionProfile = IDL.Record({
    'name' : IDL.Text,
    'instType' : InstitutionType,
    'interestedCrops' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChatMessage' : IDL.Func(
        [IDL.Text, IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null })],
        [],
        [],
      ),
    'addKnowledgeHubArticle' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Vec(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'addSalaryRecord' : IDL.Func([IDL.Principal, SalaryRecord], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'browseOrganicProduce' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ProduceListing))],
        ['query'],
      ),
    'browseProduce' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ProduceListing))],
        ['query'],
      ),
    'createOrUpdateCompensation' : IDL.Func(
        [IDL.Principal, IDL.Nat, InsurancePlan, IDL.Nat],
        [],
        [],
      ),
    'deleteFarmer' : IDL.Func([IDL.Principal], [], []),
    'deleteInstitution' : IDL.Func([IDL.Principal], [], []),
    'deleteProduceListing' : IDL.Func([IDL.Nat], [], []),
    'getAllKnowledgeHubArticles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, KnowledgeHubArticle))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getDashboardMetrics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalOrganicListings' : IDL.Nat,
            'totalListings' : IDL.Nat,
            'urbanFarmers' : IDL.Nat,
            'totalInstitutions' : IDL.Nat,
            'totalRequests' : IDL.Nat,
            'totalFarmers' : IDL.Nat,
            'ruralFarmers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getFarmerCompensation' : IDL.Func(
        [],
        [IDL.Opt(FarmerCompensation)],
        ['query'],
      ),
    'getFarmerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(FarmerProfile)],
        ['query'],
      ),
    'getMyAssistanceRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, AssistanceRequest))],
        ['query'],
      ),
    'getMyListings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ProduceListing))],
        ['query'],
      ),
    'getMyPFAccount' : IDL.Func([], [IDL.Opt(PFAccount)], ['query']),
    'getSpecificKnowledgeHubArticle' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(KnowledgeHubArticle)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listProduce' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Bool,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'registerFarmer' : IDL.Func([FarmerProfile], [], []),
    'registerInstitution' : IDL.Func([InstitutionProfile], [], []),
    'requestProduce' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAssistanceRequest' : IDL.Func(
        [
          AssistanceType,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'updateAssistanceRequestStatus' : IDL.Func(
        [IDL.Nat, AssistanceRequestStatus],
        [],
        [],
      ),
    'updatePFAccount' : IDL.Func(
        [IDL.Principal, IDL.Vec(PFHistoryRecord)],
        [],
        [],
      ),
    'updateProduceListing' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };