/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssistanceRequest {
  'status' : AssistanceRequestStatus,
  'submittedTime' : Time,
  'requestId' : bigint,
  'videoExplanation' : [] | [ExternalBlob],
  'supportingImages' : Array<ExternalBlob>,
  'description' : string,
  'farmer' : Principal,
  'assistanceType' : AssistanceType,
}
export type AssistanceRequestStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type AssistanceType = { 'other' : null } |
  { 'technicalSupport' : null } |
  { 'postHarvestManagement' : null } |
  { 'equipmentLoan' : null };
export interface ChatMessage {
  'user' : Principal,
  'messageType' : { 'user' : null } |
    { 'assistant' : null },
  'message' : string,
  'timestamp' : Time,
}
export type ExternalBlob = Uint8Array;
export type FarmLocation = { 'urban' : null } |
  { 'rural' : null };
export interface FarmerCompensation {
  'active' : boolean,
  'totalCompensation' : bigint,
  'pfContribution' : bigint,
  'salaryHistory' : Array<SalaryRecord>,
  'insuranceCoverage' : InsurancePlan,
  'farmer' : Principal,
  'baseSalary' : bigint,
}
export interface FarmerProfile {
  'farmSize' : bigint,
  'methods' : FarmingMethods,
  'name' : string,
  'cropTypes' : Array<string>,
  'profilePicture' : [] | [ExternalBlob],
  'location' : FarmLocation,
}
export type FarmingMethods = { 'mixed' : null } |
  { 'organic' : null } |
  { 'conventional' : null };
export interface InstitutionProfile {
  'name' : string,
  'instType' : InstitutionType,
  'interestedCrops' : Array<string>,
}
export type InstitutionType = { 'school' : null } |
  { 'court' : null } |
  { 'university' : null } |
  { 'governmentOffice' : null } |
  { 'temple' : null } |
  { 'college' : null };
export interface InsurancePlan {
  'coverageAmount' : bigint,
  'planType' : { 'premium' : null } |
    { 'basic' : null } |
    { 'comprehensive' : null },
  'monthlyPremium' : bigint,
}
export interface KnowledgeHubArticle {
  'title' : string,
  'content' : string,
  'author' : string,
  'articleId' : bigint,
  'videos' : Array<ExternalBlob>,
  'images' : Array<ExternalBlob>,
}
export interface PFAccount {
  'yearlyStatements' : Array<PFHistoryRecord>,
  'totalBalance' : bigint,
  'farmer' : Principal,
}
export interface PFHistoryRecord {
  'month' : bigint,
  'balance' : bigint,
  'accruedInterest' : bigint,
  'year' : bigint,
  'withdrawal' : bigint,
  'contributionAmount' : bigint,
}
export interface ProduceListing {
  'organic' : boolean,
  'listingId' : bigint,
  'crop' : string,
  'listingImage' : [] | [ExternalBlob],
  'videoTour' : [] | [ExternalBlob],
  'quantity' : bigint,
  'price' : bigint,
  'farmer' : Principal,
}
export interface SalaryRecord {
  'compensation' : bigint,
  'month' : bigint,
  'salary' : bigint,
  'totalCompensation' : bigint,
  'year' : bigint,
  'paymentDate' : Time,
  'bonuses' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'userType' : { 'other' : null } |
    { 'institution' : null } |
    { 'farmer' : null },
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChatMessage' : ActorMethod<
    [string, { 'user' : null } | { 'assistant' : null }],
    undefined
  >,
  'addKnowledgeHubArticle' : ActorMethod<
    [string, string, string, Array<ExternalBlob>, Array<ExternalBlob>],
    bigint
  >,
  'addSalaryRecord' : ActorMethod<[Principal, SalaryRecord], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'browseOrganicProduce' : ActorMethod<[], Array<[bigint, ProduceListing]>>,
  'browseProduce' : ActorMethod<[], Array<[bigint, ProduceListing]>>,
  'createOrUpdateCompensation' : ActorMethod<
    [Principal, bigint, InsurancePlan, bigint],
    undefined
  >,
  'deleteFarmer' : ActorMethod<[Principal], undefined>,
  'deleteInstitution' : ActorMethod<[Principal], undefined>,
  'deleteProduceListing' : ActorMethod<[bigint], undefined>,
  'getAllKnowledgeHubArticles' : ActorMethod<
    [],
    Array<[bigint, KnowledgeHubArticle]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getDashboardMetrics' : ActorMethod<
    [],
    {
      'totalOrganicListings' : bigint,
      'totalListings' : bigint,
      'urbanFarmers' : bigint,
      'totalInstitutions' : bigint,
      'totalRequests' : bigint,
      'totalFarmers' : bigint,
      'ruralFarmers' : bigint,
    }
  >,
  'getFarmerCompensation' : ActorMethod<[], [] | [FarmerCompensation]>,
  'getFarmerProfile' : ActorMethod<[Principal], [] | [FarmerProfile]>,
  'getMyAssistanceRequests' : ActorMethod<
    [],
    Array<[bigint, AssistanceRequest]>
  >,
  'getMyListings' : ActorMethod<[], Array<[bigint, ProduceListing]>>,
  'getMyPFAccount' : ActorMethod<[], [] | [PFAccount]>,
  'getSpecificKnowledgeHubArticle' : ActorMethod<
    [bigint],
    [] | [KnowledgeHubArticle]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listProduce' : ActorMethod<
    [string, bigint, bigint, boolean, [] | [ExternalBlob], [] | [ExternalBlob]],
    bigint
  >,
  'registerFarmer' : ActorMethod<[FarmerProfile], undefined>,
  'registerInstitution' : ActorMethod<[InstitutionProfile], undefined>,
  'requestProduce' : ActorMethod<[bigint, bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAssistanceRequest' : ActorMethod<
    [AssistanceType, string, Array<ExternalBlob>, [] | [ExternalBlob]],
    bigint
  >,
  'updateAssistanceRequestStatus' : ActorMethod<
    [bigint, AssistanceRequestStatus],
    undefined
  >,
  'updatePFAccount' : ActorMethod<
    [Principal, Array<PFHistoryRecord>],
    undefined
  >,
  'updateProduceListing' : ActorMethod<[bigint, bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];