/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PFAccount {
    yearlyStatements: Array<PFHistoryRecord>;
    totalBalance: bigint;
    farmer: Principal;
}
export interface SalaryRecord {
    compensation: bigint;
    month: bigint;
    salary: bigint;
    totalCompensation: bigint;
    year: bigint;
    paymentDate: Time;
    bonuses: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface ProduceListing {
    organic: boolean;
    listingId: bigint;
    crop: string;
    listingImage?: ExternalBlob;
    videoTour?: ExternalBlob;
    quantity: bigint;
    price: bigint;
    farmer: Principal;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface FarmerCompensation {
    active: boolean;
    totalCompensation: bigint;
    pfContribution: bigint;
    salaryHistory: Array<SalaryRecord>;
    insuranceCoverage: InsurancePlan;
    farmer: Principal;
    baseSalary: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface KnowledgeHubArticle {
    title: string;
    content: string;
    author: string;
    articleId: bigint;
    videos: Array<ExternalBlob>;
    images: Array<ExternalBlob>;
}
export interface InsurancePlan {
    coverageAmount: bigint;
    planType: Variant_premium_basic_comprehensive;
    monthlyPremium: bigint;
}
export interface AssistanceRequest {
    status: AssistanceRequestStatus;
    submittedTime: Time;
    requestId: bigint;
    videoExplanation?: ExternalBlob;
    supportingImages: Array<ExternalBlob>;
    description: string;
    farmer: Principal;
    assistanceType: AssistanceType;
}
export interface FarmerProfile {
    farmSize: bigint;
    methods: FarmingMethods;
    name: string;
    cropTypes: Array<string>;
    profilePicture?: ExternalBlob;
    location: FarmLocation;
}
export interface ChatMessage {
    user: Principal;
    messageType: Variant_user_assistant;
    message: string;
    timestamp: Time;
}
export interface PFHistoryRecord {
    month: bigint;
    balance: bigint;
    accruedInterest: bigint;
    year: bigint;
    withdrawal: bigint;
    contributionAmount: bigint;
}
export interface UserProfile {
    userType: Variant_other_institution_farmer;
    name: string;
}
export interface InstitutionProfile {
    name: string;
    instType: InstitutionType;
    interestedCrops: Array<string>;
}
export enum AssistanceRequestStatus {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum AssistanceType {
    other = "other",
    technicalSupport = "technicalSupport",
    postHarvestManagement = "postHarvestManagement",
    equipmentLoan = "equipmentLoan"
}
export enum FarmLocation {
    urban = "urban",
    rural = "rural"
}
export enum FarmingMethods {
    mixed = "mixed",
    organic = "organic",
    conventional = "conventional"
}
export enum InstitutionType {
    school = "school",
    court = "court",
    university = "university",
    governmentOffice = "governmentOffice",
    temple = "temple",
    college = "college"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_other_institution_farmer {
    other = "other",
    institution = "institution",
    farmer = "farmer"
}
export enum Variant_premium_basic_comprehensive {
    premium = "premium",
    basic = "basic",
    comprehensive = "comprehensive"
}
export enum Variant_user_assistant {
    user = "user",
    assistant = "assistant"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addChatMessage(message: string, messageType: Variant_user_assistant): Promise<void>;
    addKnowledgeHubArticle(title: string, content: string, author: string, images: Array<ExternalBlob>, videos: Array<ExternalBlob>): Promise<bigint>;
    addSalaryRecord(farmer: Principal, salaryRecord: SalaryRecord): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    browseOrganicProduce(): Promise<Array<[bigint, ProduceListing]>>;
    browseProduce(): Promise<Array<[bigint, ProduceListing]>>;
    createOrUpdateCompensation(farmer: Principal, baseSalary: bigint, coverage: InsurancePlan, pfContribution: bigint): Promise<void>;
    deleteFarmer(farmer: Principal): Promise<void>;
    deleteInstitution(institution: Principal): Promise<void>;
    deleteProduceListing(listingId: bigint): Promise<void>;
    getAllKnowledgeHubArticles(): Promise<Array<[bigint, KnowledgeHubArticle]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatHistory(): Promise<Array<ChatMessage>>;
    getDashboardMetrics(): Promise<{
        totalOrganicListings: bigint;
        totalListings: bigint;
        urbanFarmers: bigint;
        totalInstitutions: bigint;
        totalRequests: bigint;
        totalFarmers: bigint;
        ruralFarmers: bigint;
    }>;
    getFarmerCompensation(): Promise<FarmerCompensation | null>;
    getFarmerProfile(farmer: Principal): Promise<FarmerProfile | null>;
    getMyAssistanceRequests(): Promise<Array<[bigint, AssistanceRequest]>>;
    getMyListings(): Promise<Array<[bigint, ProduceListing]>>;
    getMyPFAccount(): Promise<PFAccount | null>;
    getSpecificKnowledgeHubArticle(articleId: bigint): Promise<KnowledgeHubArticle | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listProduce(crop: string, quantity: bigint, price: bigint, organic: boolean, listingImage: ExternalBlob | null, videoTour: ExternalBlob | null): Promise<bigint>;
    registerFarmer(profile: FarmerProfile): Promise<void>;
    registerInstitution(profile: InstitutionProfile): Promise<void>;
    requestProduce(listingId: bigint, requestedQuantity: bigint): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitAssistanceRequest(assistanceType: AssistanceType, description: string, images: Array<ExternalBlob>, video: ExternalBlob | null): Promise<bigint>;
    updateAssistanceRequestStatus(requestId: bigint, status: AssistanceRequestStatus): Promise<void>;
    updatePFAccount(farmer: Principal, records: Array<PFHistoryRecord>): Promise<void>;
    updateProduceListing(listingId: bigint, quantity: bigint, price: bigint): Promise<void>;
}
import type { AssistanceRequest as _AssistanceRequest, AssistanceRequestStatus as _AssistanceRequestStatus, AssistanceType as _AssistanceType, ChatMessage as _ChatMessage, ExternalBlob as _ExternalBlob, FarmLocation as _FarmLocation, FarmerCompensation as _FarmerCompensation, FarmerProfile as _FarmerProfile, FarmingMethods as _FarmingMethods, InstitutionProfile as _InstitutionProfile, InstitutionType as _InstitutionType, InsurancePlan as _InsurancePlan, KnowledgeHubArticle as _KnowledgeHubArticle, PFAccount as _PFAccount, ProduceListing as _ProduceListing, SalaryRecord as _SalaryRecord, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addChatMessage(arg0: string, arg1: Variant_user_assistant): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addChatMessage(arg0, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChatMessage(arg0, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addKnowledgeHubArticle(arg0: string, arg1: string, arg2: string, arg3: Array<ExternalBlob>, arg4: Array<ExternalBlob>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addKnowledgeHubArticle(arg0, arg1, arg2, await to_candid_vec_n9(this._uploadFile, this._downloadFile, arg3), await to_candid_vec_n9(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addKnowledgeHubArticle(arg0, arg1, arg2, await to_candid_vec_n9(this._uploadFile, this._downloadFile, arg3), await to_candid_vec_n9(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async addSalaryRecord(arg0: Principal, arg1: SalaryRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSalaryRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSalaryRecord(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async browseOrganicProduce(): Promise<Array<[bigint, ProduceListing]>> {
        if (this.processError) {
            try {
                const result = await this.actor.browseOrganicProduce();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.browseOrganicProduce();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async browseProduce(): Promise<Array<[bigint, ProduceListing]>> {
        if (this.processError) {
            try {
                const result = await this.actor.browseProduce();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.browseProduce();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrUpdateCompensation(arg0: Principal, arg1: bigint, arg2: InsurancePlan, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateCompensation(arg0, arg1, to_candid_InsurancePlan_n19(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateCompensation(arg0, arg1, to_candid_InsurancePlan_n19(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async deleteFarmer(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFarmer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFarmer(arg0);
            return result;
        }
    }
    async deleteInstitution(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInstitution(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInstitution(arg0);
            return result;
        }
    }
    async deleteProduceListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduceListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduceListing(arg0);
            return result;
        }
    }
    async getAllKnowledgeHubArticles(): Promise<Array<[bigint, KnowledgeHubArticle]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKnowledgeHubArticles();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKnowledgeHubArticles();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatHistory(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistory();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistory();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardMetrics(): Promise<{
        totalOrganicListings: bigint;
        totalListings: bigint;
        urbanFarmers: bigint;
        totalInstitutions: bigint;
        totalRequests: bigint;
        totalFarmers: bigint;
        ruralFarmers: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardMetrics();
            return result;
        }
    }
    async getFarmerCompensation(): Promise<FarmerCompensation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFarmerCompensation();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFarmerCompensation();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFarmerProfile(arg0: Principal): Promise<FarmerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFarmerProfile(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFarmerProfile(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAssistanceRequests(): Promise<Array<[bigint, AssistanceRequest]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAssistanceRequests();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAssistanceRequests();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyListings(): Promise<Array<[bigint, ProduceListing]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyListings();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyListings();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPFAccount(): Promise<PFAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPFAccount();
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPFAccount();
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSpecificKnowledgeHubArticle(arg0: bigint): Promise<KnowledgeHubArticle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpecificKnowledgeHubArticle(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpecificKnowledgeHubArticle(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listProduce(arg0: string, arg1: bigint, arg2: bigint, arg3: boolean, arg4: ExternalBlob | null, arg5: ExternalBlob | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.listProduce(arg0, arg1, arg2, arg3, await to_candid_opt_n60(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n60(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProduce(arg0, arg1, arg2, arg3, await to_candid_opt_n60(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n60(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async registerFarmer(arg0: FarmerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFarmer(await to_candid_FarmerProfile_n61(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFarmer(await to_candid_FarmerProfile_n61(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async registerInstitution(arg0: InstitutionProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerInstitution(to_candid_InstitutionProfile_n67(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerInstitution(to_candid_InstitutionProfile_n67(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async requestProduce(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.requestProduce(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestProduce(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n71(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n71(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitAssistanceRequest(arg0: AssistanceType, arg1: string, arg2: Array<ExternalBlob>, arg3: ExternalBlob | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAssistanceRequest(to_candid_AssistanceType_n74(this._uploadFile, this._downloadFile, arg0), arg1, await to_candid_vec_n9(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n60(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAssistanceRequest(to_candid_AssistanceType_n74(this._uploadFile, this._downloadFile, arg0), arg1, await to_candid_vec_n9(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n60(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateAssistanceRequestStatus(arg0: bigint, arg1: AssistanceRequestStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssistanceRequestStatus(arg0, to_candid_AssistanceRequestStatus_n76(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssistanceRequestStatus(arg0, to_candid_AssistanceRequestStatus_n76(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePFAccount(arg0: Principal, arg1: Array<PFHistoryRecord>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePFAccount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePFAccount(arg0, arg1);
            return result;
        }
    }
    async updateProduceListing(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduceListing(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduceListing(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AssistanceRequestStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssistanceRequestStatus): AssistanceRequestStatus {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
async function from_candid_AssistanceRequest_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssistanceRequest): Promise<AssistanceRequest> {
    return await from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_AssistanceType_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssistanceType): AssistanceType {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_ChatMessage_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FarmLocation_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FarmLocation): FarmLocation {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_FarmerCompensation_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FarmerCompensation): FarmerCompensation {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
async function from_candid_FarmerProfile_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FarmerProfile): Promise<FarmerProfile> {
    return await from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_FarmingMethods_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FarmingMethods): FarmingMethods {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_InsurancePlan_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InsurancePlan): InsurancePlan {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_KnowledgeHubArticle_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KnowledgeHubArticle): Promise<KnowledgeHubArticle> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ProduceListing_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProduceListing): Promise<ProduceListing> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FarmerCompensation]): FarmerCompensation | null {
    return value.length === 0 ? null : from_candid_FarmerCompensation_n38(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FarmerProfile]): Promise<FarmerProfile | null> {
    return value.length === 0 ? null : await from_candid_FarmerProfile_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PFAccount]): PFAccount | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_KnowledgeHubArticle]): Promise<KnowledgeHubArticle | null> {
    return value.length === 0 ? null : await from_candid_KnowledgeHubArticle_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    organic: boolean;
    listingId: bigint;
    crop: string;
    listingImage: [] | [_ExternalBlob];
    videoTour: [] | [_ExternalBlob];
    quantity: bigint;
    price: bigint;
    farmer: Principal;
}): Promise<{
    organic: boolean;
    listingId: bigint;
    crop: string;
    listingImage?: ExternalBlob;
    videoTour?: ExternalBlob;
    quantity: bigint;
    price: bigint;
    farmer: Principal;
}> {
    return {
        organic: value.organic,
        listingId: value.listingId,
        crop: value.crop,
        listingImage: record_opt_to_undefined(await from_candid_opt_n17(_uploadFile, _downloadFile, value.listingImage)),
        videoTour: record_opt_to_undefined(await from_candid_opt_n17(_uploadFile, _downloadFile, value.videoTour)),
        quantity: value.quantity,
        price: value.price,
        farmer: value.farmer
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    author: string;
    articleId: bigint;
    videos: Array<_ExternalBlob>;
    images: Array<_ExternalBlob>;
}): Promise<{
    title: string;
    content: string;
    author: string;
    articleId: bigint;
    videos: Array<ExternalBlob>;
    images: Array<ExternalBlob>;
}> {
    return {
        title: value.title,
        content: value.content,
        author: value.author,
        articleId: value.articleId,
        videos: await from_candid_vec_n26(_uploadFile, _downloadFile, value.videos),
        images: await from_candid_vec_n26(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: {
        other: null;
    } | {
        institution: null;
    } | {
        farmer: null;
    };
    name: string;
}): {
    userType: Variant_other_institution_farmer;
    name: string;
} {
    return {
        userType: from_candid_variant_n30(_uploadFile, _downloadFile, value.userType),
        name: value.name
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: Principal;
    messageType: {
        user: null;
    } | {
        assistant: null;
    };
    message: string;
    timestamp: _Time;
}): {
    user: Principal;
    messageType: Variant_user_assistant;
    message: string;
    timestamp: Time;
} {
    return {
        user: value.user,
        messageType: from_candid_variant_n36(_uploadFile, _downloadFile, value.messageType),
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    totalCompensation: bigint;
    pfContribution: bigint;
    salaryHistory: Array<_SalaryRecord>;
    insuranceCoverage: _InsurancePlan;
    farmer: Principal;
    baseSalary: bigint;
}): {
    active: boolean;
    totalCompensation: bigint;
    pfContribution: bigint;
    salaryHistory: Array<SalaryRecord>;
    insuranceCoverage: InsurancePlan;
    farmer: Principal;
    baseSalary: bigint;
} {
    return {
        active: value.active,
        totalCompensation: value.totalCompensation,
        pfContribution: value.pfContribution,
        salaryHistory: value.salaryHistory,
        insuranceCoverage: from_candid_InsurancePlan_n40(_uploadFile, _downloadFile, value.insuranceCoverage),
        farmer: value.farmer,
        baseSalary: value.baseSalary
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    coverageAmount: bigint;
    planType: {
        premium: null;
    } | {
        basic: null;
    } | {
        comprehensive: null;
    };
    monthlyPremium: bigint;
}): {
    coverageAmount: bigint;
    planType: Variant_premium_basic_comprehensive;
    monthlyPremium: bigint;
} {
    return {
        coverageAmount: value.coverageAmount,
        planType: from_candid_variant_n42(_uploadFile, _downloadFile, value.planType),
        monthlyPremium: value.monthlyPremium
    };
}
async function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    farmSize: bigint;
    methods: _FarmingMethods;
    name: string;
    cropTypes: Array<string>;
    profilePicture: [] | [_ExternalBlob];
    location: _FarmLocation;
}): Promise<{
    farmSize: bigint;
    methods: FarmingMethods;
    name: string;
    cropTypes: Array<string>;
    profilePicture?: ExternalBlob;
    location: FarmLocation;
}> {
    return {
        farmSize: value.farmSize,
        methods: from_candid_FarmingMethods_n46(_uploadFile, _downloadFile, value.methods),
        name: value.name,
        cropTypes: value.cropTypes,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n17(_uploadFile, _downloadFile, value.profilePicture)),
        location: from_candid_FarmLocation_n48(_uploadFile, _downloadFile, value.location)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AssistanceRequestStatus;
    submittedTime: _Time;
    requestId: bigint;
    videoExplanation: [] | [_ExternalBlob];
    supportingImages: Array<_ExternalBlob>;
    description: string;
    farmer: Principal;
    assistanceType: _AssistanceType;
}): Promise<{
    status: AssistanceRequestStatus;
    submittedTime: Time;
    requestId: bigint;
    videoExplanation?: ExternalBlob;
    supportingImages: Array<ExternalBlob>;
    description: string;
    farmer: Principal;
    assistanceType: AssistanceType;
}> {
    return {
        status: from_candid_AssistanceRequestStatus_n54(_uploadFile, _downloadFile, value.status),
        submittedTime: value.submittedTime,
        requestId: value.requestId,
        videoExplanation: record_opt_to_undefined(await from_candid_opt_n17(_uploadFile, _downloadFile, value.videoExplanation)),
        supportingImages: await from_candid_vec_n26(_uploadFile, _downloadFile, value.supportingImages),
        description: value.description,
        farmer: value.farmer,
        assistanceType: from_candid_AssistanceType_n56(_uploadFile, _downloadFile, value.assistanceType)
    };
}
async function from_candid_tuple_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _ProduceListing]): Promise<[bigint, ProduceListing]> {
    return [
        value[0],
        await from_candid_ProduceListing_n15(_uploadFile, _downloadFile, value[1])
    ];
}
async function from_candid_tuple_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _KnowledgeHubArticle]): Promise<[bigint, KnowledgeHubArticle]> {
    return [
        value[0],
        await from_candid_KnowledgeHubArticle_n24(_uploadFile, _downloadFile, value[1])
    ];
}
async function from_candid_tuple_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _AssistanceRequest]): Promise<[bigint, AssistanceRequest]> {
    return [
        value[0],
        await from_candid_AssistanceRequest_n52(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    institution: null;
} | {
    farmer: null;
}): Variant_other_institution_farmer {
    return "other" in value ? Variant_other_institution_farmer.other : "institution" in value ? Variant_other_institution_farmer.institution : "farmer" in value ? Variant_other_institution_farmer.farmer : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    assistant: null;
}): Variant_user_assistant {
    return "user" in value ? Variant_user_assistant.user : "assistant" in value ? Variant_user_assistant.assistant : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    basic: null;
} | {
    comprehensive: null;
}): Variant_premium_basic_comprehensive {
    return "premium" in value ? Variant_premium_basic_comprehensive.premium : "basic" in value ? Variant_premium_basic_comprehensive.basic : "comprehensive" in value ? Variant_premium_basic_comprehensive.comprehensive : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mixed: null;
} | {
    organic: null;
} | {
    conventional: null;
}): FarmingMethods {
    return "mixed" in value ? FarmingMethods.mixed : "organic" in value ? FarmingMethods.organic : "conventional" in value ? FarmingMethods.conventional : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    urban: null;
} | {
    rural: null;
}): FarmLocation {
    return "urban" in value ? FarmLocation.urban : "rural" in value ? FarmLocation.rural : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): AssistanceRequestStatus {
    return "pending" in value ? AssistanceRequestStatus.pending : "completed" in value ? AssistanceRequestStatus.completed : "inProgress" in value ? AssistanceRequestStatus.inProgress : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    technicalSupport: null;
} | {
    postHarvestManagement: null;
} | {
    equipmentLoan: null;
}): AssistanceType {
    return "other" in value ? AssistanceType.other : "technicalSupport" in value ? AssistanceType.technicalSupport : "postHarvestManagement" in value ? AssistanceType.postHarvestManagement : "equipmentLoan" in value ? AssistanceType.equipmentLoan : value;
}
async function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _ProduceListing]>): Promise<Array<[bigint, ProduceListing]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n14(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _KnowledgeHubArticle]>): Promise<Array<[bigint, KnowledgeHubArticle]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n23(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n34(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _AssistanceRequest]>): Promise<Array<[bigint, AssistanceRequest]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n51(_uploadFile, _downloadFile, x)));
}
function to_candid_AssistanceRequestStatus_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssistanceRequestStatus): _AssistanceRequestStatus {
    return to_candid_variant_n77(_uploadFile, _downloadFile, value);
}
function to_candid_AssistanceType_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssistanceType): _AssistanceType {
    return to_candid_variant_n75(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FarmLocation_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FarmLocation): _FarmLocation {
    return to_candid_variant_n66(_uploadFile, _downloadFile, value);
}
async function to_candid_FarmerProfile_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FarmerProfile): Promise<_FarmerProfile> {
    return await to_candid_record_n62(_uploadFile, _downloadFile, value);
}
function to_candid_FarmingMethods_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FarmingMethods): _FarmingMethods {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid_InstitutionProfile_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InstitutionProfile): _InstitutionProfile {
    return to_candid_record_n68(_uploadFile, _downloadFile, value);
}
function to_candid_InstitutionType_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InstitutionType): _InstitutionType {
    return to_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function to_candid_InsurancePlan_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InsurancePlan): _InsurancePlan {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n72(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value));
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    coverageAmount: bigint;
    planType: Variant_premium_basic_comprehensive;
    monthlyPremium: bigint;
}): {
    coverageAmount: bigint;
    planType: {
        premium: null;
    } | {
        basic: null;
    } | {
        comprehensive: null;
    };
    monthlyPremium: bigint;
} {
    return {
        coverageAmount: value.coverageAmount,
        planType: to_candid_variant_n21(_uploadFile, _downloadFile, value.planType),
        monthlyPremium: value.monthlyPremium
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    farmSize: bigint;
    methods: FarmingMethods;
    name: string;
    cropTypes: Array<string>;
    profilePicture?: ExternalBlob;
    location: FarmLocation;
}): Promise<{
    farmSize: bigint;
    methods: _FarmingMethods;
    name: string;
    cropTypes: Array<string>;
    profilePicture: [] | [_ExternalBlob];
    location: _FarmLocation;
}> {
    return {
        farmSize: value.farmSize,
        methods: to_candid_FarmingMethods_n63(_uploadFile, _downloadFile, value.methods),
        name: value.name,
        cropTypes: value.cropTypes,
        profilePicture: value.profilePicture ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.profilePicture)) : candid_none(),
        location: to_candid_FarmLocation_n65(_uploadFile, _downloadFile, value.location)
    };
}
function to_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    instType: InstitutionType;
    interestedCrops: Array<string>;
}): {
    name: string;
    instType: _InstitutionType;
    interestedCrops: Array<string>;
} {
    return {
        name: value.name,
        instType: to_candid_InstitutionType_n69(_uploadFile, _downloadFile, value.instType),
        interestedCrops: value.interestedCrops
    };
}
function to_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: Variant_other_institution_farmer;
    name: string;
}): {
    userType: {
        other: null;
    } | {
        institution: null;
    } | {
        farmer: null;
    };
    name: string;
} {
    return {
        userType: to_candid_variant_n73(_uploadFile, _downloadFile, value.userType),
        name: value.name
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_premium_basic_comprehensive): {
    premium: null;
} | {
    basic: null;
} | {
    comprehensive: null;
} {
    return value == Variant_premium_basic_comprehensive.premium ? {
        premium: null
    } : value == Variant_premium_basic_comprehensive.basic ? {
        basic: null
    } : value == Variant_premium_basic_comprehensive.comprehensive ? {
        comprehensive: null
    } : value;
}
function to_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FarmingMethods): {
    mixed: null;
} | {
    organic: null;
} | {
    conventional: null;
} {
    return value == FarmingMethods.mixed ? {
        mixed: null
    } : value == FarmingMethods.organic ? {
        organic: null
    } : value == FarmingMethods.conventional ? {
        conventional: null
    } : value;
}
function to_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FarmLocation): {
    urban: null;
} | {
    rural: null;
} {
    return value == FarmLocation.urban ? {
        urban: null
    } : value == FarmLocation.rural ? {
        rural: null
    } : value;
}
function to_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InstitutionType): {
    school: null;
} | {
    court: null;
} | {
    university: null;
} | {
    governmentOffice: null;
} | {
    temple: null;
} | {
    college: null;
} {
    return value == InstitutionType.school ? {
        school: null
    } : value == InstitutionType.court ? {
        court: null
    } : value == InstitutionType.university ? {
        university: null
    } : value == InstitutionType.governmentOffice ? {
        governmentOffice: null
    } : value == InstitutionType.temple ? {
        temple: null
    } : value == InstitutionType.college ? {
        college: null
    } : value;
}
function to_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_other_institution_farmer): {
    other: null;
} | {
    institution: null;
} | {
    farmer: null;
} {
    return value == Variant_other_institution_farmer.other ? {
        other: null
    } : value == Variant_other_institution_farmer.institution ? {
        institution: null
    } : value == Variant_other_institution_farmer.farmer ? {
        farmer: null
    } : value;
}
function to_candid_variant_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssistanceType): {
    other: null;
} | {
    technicalSupport: null;
} | {
    postHarvestManagement: null;
} | {
    equipmentLoan: null;
} {
    return value == AssistanceType.other ? {
        other: null
    } : value == AssistanceType.technicalSupport ? {
        technicalSupport: null
    } : value == AssistanceType.postHarvestManagement ? {
        postHarvestManagement: null
    } : value == AssistanceType.equipmentLoan ? {
        equipmentLoan: null
    } : value;
}
function to_candid_variant_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssistanceRequestStatus): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == AssistanceRequestStatus.pending ? {
        pending: null
    } : value == AssistanceRequestStatus.completed ? {
        completed: null
    } : value == AssistanceRequestStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_user_assistant): {
    user: null;
} | {
    assistant: null;
} {
    return value == Variant_user_assistant.user ? {
        user: null
    } : value == Variant_user_assistant.assistant ? {
        assistant: null
    } : value;
}
async function to_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
